# Generated by Django 5.0.4 on 2024-04-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ren",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                ("pub_data", models.DateField(null=True, verbose_name="时间")),
            ],
            options={
                "verbose_name": "人工名称",
                "verbose_name_plural": "人工名称",
                "db_table": "human",
            },
        ),
    ]
